### ISSUE TITLE
Parse Error with Unifi Controller 6.2.26

### ISSUE THREAD

**Issue by e36Alex** [klenzel/check_unifi45#1]
Hi,

i tried out your plugin on my linux hosted unifi controller and my icinga2 installation.

The check is executed and i get a response, but i also get a parse error:
`
parse error: Invalid numeric literal at line 1, column 10
/usr/lib/nagios/plugins/check_unifi45.sh: Zeile 163: [: !=: Einstelliger (unÃ¤rer) Operator erwartet.
OK: FÃ¼r den Unifi-Controller sind keine Updates verfÃ¼gbar`

Is something wrong with my configuration or is the plugin not compatible with latest version of the unifi controller?

Thanks, Alex

**Comment by e36Alex** [comment]
No idea, anyone?

**Comment by klenzel** [comment]
Check out my new Version of this Script für Unifi Controllers >=6
This should solve your problem.

https://github.com/klenzel/check_unifi65
